# generated by datamodel-codegen:
#   filename:  otm_schema.json
#   timestamp: 2024-10-14T20:47:35+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel


class Project(BaseModel):
    name: str
    id: str
    description: Optional[str] = None
    owner: Optional[str] = None
    ownerContact: Optional[str] = None
    tags: Optional[List[str]] = None
    attributes: Optional[Dict[str, Any]] = None


class Repository(BaseModel):
    url: Optional[str]


class Risk(BaseModel):
    confidentiality: float
    integrity: float
    availability: float
    comment: Optional[str] = None


class Asset(BaseModel):
    name: str
    id: str
    description: Optional[str] = None
    risk: Risk
    attributes: Optional[Dict[str, Any]] = None


class Risk1(BaseModel):
    trustRating: float


class Risk2(BaseModel):
    likelihood: Optional[float]
    likelihoodComment: Optional[str] = None
    impact: float
    impactComment: Optional[str] = None


class Threat1(BaseModel):
    id: str
    name: str
    description: Optional[str] = None
    categories: Optional[List[Optional[str]]] = None
    cwes: Optional[List[Optional[str]]] = None
    risk: Risk2
    tags: Optional[List[Optional[str]]] = None
    attributes: Optional[Dict[str, Any]] = None


class Mitigation(BaseModel):
    id: str
    name: str
    description: Optional[str] = None
    riskReduction: float
    attributes: Optional[Dict[str, Any]] = None


class Size(BaseModel):
    width: float
    height: float


class Parent1(BaseModel):
    trustZone: str
    component: Optional[str] = None


class Parent2(BaseModel):
    trustZone: Optional[str] = None
    component: str


class Parent(BaseModel):
    __root__: Union[Parent1, Parent2]


class Position(BaseModel):
    x: float
    y: float


class RepresentationElement(BaseModel):
    representation: str
    name: Optional[str] = None
    id: str
    position: Optional[Position] = None
    size: Optional[Size] = None
    file: Optional[str] = None
    line: Optional[float] = None
    codeSnippet: Optional[str] = None
    attributes: Optional[Dict[str, Any]] = None


class Mitigation1(BaseModel):
    mitigation: Optional[str]
    state: Optional[str]


class Threat(BaseModel):
    threat: str
    state: str
    mitigations: Optional[List[Optional[Mitigation1]]] = None


class AssetInstance(BaseModel):
    processed: Optional[List[Optional[str]]] = None
    stored: Optional[List[Optional[str]]] = None


class Representation(BaseModel):
    name: str
    id: str
    type: str
    description: Optional[str] = None
    size: Optional[Size] = None
    repository: Optional[Repository] = None
    attributes: Optional[Dict[str, Any]] = None


class TrustZone(BaseModel):
    id: str
    name: str
    type: Optional[str] = None
    description: Optional[str] = None
    risk: Risk1
    parent: Optional[Parent] = None
    representations: Optional[List[RepresentationElement]] = None
    attributes: Optional[Dict[str, Any]] = None


class Component(BaseModel):
    id: str
    name: str
    type: str
    description: Optional[str] = None
    parent: Parent
    representations: Optional[List[RepresentationElement]] = None
    assets: Optional[AssetInstance] = None
    threats: Optional[List[Threat]] = None
    tags: Optional[List[Optional[str]]] = None
    attributes: Optional[Dict[str, Any]] = None


class Dataflow(BaseModel):
    id: str
    name: str
    description: Optional[str] = None
    bidirectional: Optional[bool] = None
    source: str
    destination: str
    assets: Optional[List[Optional[str]]] = None
    threats: Optional[List[Threat]] = None
    tags: Optional[List[Optional[str]]] = None
    attributes: Optional[Dict[str, Any]] = None


class OpenThreatModelSpecification(BaseModel):
    otmVersion: str
    project: Project
    representations: Optional[List[Representation]] = None
    assets: Optional[List[Asset]] = None
    trustZones: Optional[List[TrustZone]] = None
    components: Optional[List[Component]] = None
    dataflows: Optional[List[Dataflow]] = None
    threats: Optional[List[Threat1]] = None
    mitigations: Optional[List[Mitigation]] = None
